name: Notify Root Repo

on:
  push:
    branches:
      - main

jobs:
  notify-root:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event to Root Repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ROOT_REPO_PAT }}" \
          https://api.github.com/repos/iol-lshh/Iol-lshh.github.io/dispatches \
          -d '{"event_type": "update_submodule"}'
